name: Terraform CI

on: [push, pull_request]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Format
        run: terraform -chdir=infra fmt -check

      - name: Terraform Init
        run: terraform -chdir=infra init -backend=false

      - name: Terraform Validate
        run: terraform -chdir=infra validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Run TFLint
        run: tflint --init && tflint

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
